title: Stefan O'Toole
position: Ph.D. Student
affiliation: Univeristy of Melbourne
email: stefan (at) student.unimelb.edu.au
keywords: phd
google_scholar: https://scholar.google.com/citations?user=-y38vGUAAAAJ&hl=en&authuser=1
github_link: https://github.com/stefanotoole
linkedin: https://linkedin.com/in/stefan-o-toole-061847109/
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/thumbnail.png
favicon_dark: ./assets/img/thumbnail.png
description: Stefan O'Toole's personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light